apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      restartPolicy: Always
      containers:
        - name: microservice1
          image: aleksanderacc/microservice1
          env:
            - name: DB_HOSTNAME
              value: "db-svc.default"
            - name: WATCHFILES_FORCE_POLLING
              value: "true"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: shop
            - name: API_ORDERS_PREFIX
              value: "/api"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: microservice1-svc
spec:
  selector:
    app: microservice1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000