name: Snyk scanning implementation
on:
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code from main branch
        uses: actions/checkout@master
      - name: Print available directories
        run: ls -la
      - name: Navigate to app directory
        run: cd ./microservice1
      - name: pwd
        run: echo $PWD
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          args: --workdir=$PWD
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
