name: Snyk scanning implementation
on:
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: print
        run: echo "${{ env.SNYK_TOKEN }}"
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env: 
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
