name: Snyk scanning implementation
on:
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print available directories
        run: ls -la
      - name: github workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: pwd
        run: echo $PWD
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true 
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif  --file=./microservice1 --severity-threshold=medium
          
