name: Snyk scanning implementation
on:
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print available directories
        run: ls -la
      - name: github workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: pwd
        run: echo $PWD
      - name: cd
        run: cd microservice1
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true 
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=requirements.txt --severity-threshold=medium
       

     # The Snyk Action will fail when vulnerabilities are found. This would prevent the SARIF upload action from running     
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
        
          sarif_file: snyk.sarif